networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
      - '/etc/letsencrypt:/etc/letsencrypt'
    depends_on:
      - backend
      - frontend
    networks:
      - dev


  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env.production
    networks:
      - dev

  frontend:
    build:
      context: ./frontend
    env_file:
        - ./frontend/.env.production
    networks:
      - dev