networks:
  dev:

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DOMAIN=api.drobi-school-tg.ru
      - NODE_ENV=production
      - TELEGRAM_API_TOKEN=7732393445:AAGEofGQzv1cBS3GyV8PYg9WP9uAZTWXvFo
      # TEST
#      - YOO_KASSA_SHOP_ID=489788
#      - YOO_KASSA_SECRET_KEY=test_giBS_YtTM-m0FZJTd-n_rWqCBUW9evd9nw9pzqQMs64
      # PROD
      - YOO_KASSA_SHOP_ID=442761
      - YOO_KASSA_SECRET_KEY=live_rPHVjsFetKvSUtgTZFYv4_W_WJVmCgBKcB0UslUSxUc
      - AIRTABLE_TOKEN=patZYS9IGZCng7Kn1.e948ed001154c94169f6092bed0608edf12be6c8c0554525062ba3a638b607fb
      - AIRTABLE_BASE=appfqififykDH9NqA
      - AIRTABLE_URL=https://api.airtable.com/v0/appfqififykDH9NqA
      - HOLLIHOP_WEBHOOK_URL=https://campus-academy.t8s.ru/Api/V2
    restart: unless-stopped
    networks:
      - dev

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - dev

  certbot:
    image: certbot/certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 6h & wait $${!}; certbot renew; done;'"
    networks:
      - dev